send_api_users_to_esp:
  cron: "0 * * * *"
  class: "ApiUsers::SendToEspWorker"
  queue: default

send_formsite_users_to_esp:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEspWorker"
  queue: default

send_leadgen_rev_site_users_to_esp:
  cron: "0 * * * *"
  class: "LeadgenRevSiteUsers::SendToEspWorker"
  queue: default

send_website_users_to_esp:
  cron: "0 * * * *"
  class: "WebsiteUsers::SendToEspWorker"
  queue: default

aweber_migrate_subscribers:
  cron: "0 0 * * *"
  class: "Aweber::MigrateSubscribersWorker"
  queue: default

aweber_collect_statistics:
  cron: "0 0 * * 1,4"
  class: "Aweber::CollectStatisticsWorker"
  queue: statistics

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

batch_send_to_adopia:
  cron: "0 */2 * * *"
  class: "Esp::BatchSendToAdopiaWorker"
  queue: leads

batch_old_send_to_netatlantic:
  cron: "0 */2 * * *"
  class: "Esp::BatchSendOldRefsToNetatlanticWorker"
  queue: leads

batch_send_to_netatlantic:
  cron: "*/10 * * * *"
  class: "Esp::BatchSendToNetatlanticWorker"
  queue: leads

send_emails_to_mailgun:
  cron: "0 10,13 * * *"
  class: "Esp::SendEmailsToMailgunWorker"
  queue: default
