send_api_users_to_esp:
  cron: "0 * * * *"
  class: "ApiUsers::SendToEspWorker"
  queue: default

send_formsite_users_to_esp:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEspWorker"
  queue: default

send_leadgen_rev_site_users_to_esp:
  cron: "0 * * * *"
  class: "LeadgenRevSiteUsers::SendToEspWorker"
  queue: default

send_website_users_to_esp:
  cron: "0 * * * *"
  class: "WebsiteUsers::SendToEspWorker"
  queue: default

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

batch_send_to_adopia:
  cron: "0 * * * *"
  class: "Esp::BatchSendToAdopiaWorker"
  queue: leads

batch_old_send_to_netatlantic:
  cron: "0 * * * *"
  class: "Esp::BatchSendOldRefsToNetatlanticWorker"
  queue: leads
