send_api_users_to_esp:
  cron: "0 * * * *"
  class: "ApiUsers::SendToEspWorker"
  queue: default

send_formsite_users_to_esp:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEspWorker"
  queue: default

aweber_migrate_subscribers:
  cron: "0 0 * * *"
  class: "Aweber::MigrateSubscribersWorker"
  queue: default

aweber_collect_statistics:
  cron: "0 0 * * 1,4"
  class: "Aweber::CollectStatisticsWorker"
  queue: statistics

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

