#send_api_users_to_esp:
#  cron: "0 * * * *"
#  class: "ApiUsers::SendToEspWorker"
#  queue: default

send_formsite_users_to_esp:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEspWorker"
  queue: default

#send_leadgen_rev_site_users_to_esp:
#  cron: "0 * * * *"
#  class: "LeadgenRevSiteUsers::SendToEspWorker"
#  queue: default

send_website_users_to_esp:
  cron: "0 * * * *"
  class: "WebsiteUsers::SendToEspWorker"
  queue: default

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

#batch_old_send_to_netatlantic:
#  cron: "0,30 * * * *"
#  class: "Esp::BatchSendOldRefsToNetatlanticWorker"
#  queue: leads

autorespond_to_inactive_recipients:
  cron: "1 * * * *"
  class: "Messages::ReminderWorker"
  queue: messages

recurring_autoresponse:
  cron: "*/10 * * * *"
  class: "Messages::RecurringAutoResponseWorker"
  queue: messages

send_users_to_waypoint:
  cron: "*/15 * * * *"
  class: "LeadgenRevSiteUsers::SendUsersToWaypoint"
  queue: cep

send_users_to_colossus:
  cron: "1 * * * *"
  class: "LeadgenRevSiteUsers::SendToColossusWorker"
  queue: colossus
