send_api_users_to_esp:
  cron: "0 * * * *"
  class: "ApiUsers::SendToEspWorker"
  queue: default

send_formsite_users_to_esp:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEspWorker"
  queue: default

send_leadgen_rev_site_users_to_esp:
  cron: "0 * * * *"
  class: "LeadgenRevSiteUsers::SendToEspWorker"
  queue: default

aweber_migrate_subscribers:
  cron: "0 0 * * *"
  class: "Aweber::MigrateSubscribersWorker"
  queue: default

aweber_collect_statistics:
  cron: "0 0 * * 1,4"
  class: "Aweber::CollectStatisticsWorker"
  queue: statistics

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

batch_send_to_adopia:
  cron: "0 6 * * *"
  class: "Esp::BatchSendToAdopiaWorker"
  queue: leads

batch_send_to_netatlantic:
  cron: "0 * * * *"
  class: "Esp::BatchSendToNetatlanticWorker"
  queue: leads

batch_send_to_netatlantic:
  cron: "*/30 * * * *"
  class: "Esp::BatchSendToAdopiaCasapiWorker"
  queue: leads