send_api_users_to_aweber:
  cron: "0 * * * *"
  class: "ApiUsers::SendToAweberWorker"
  queue: default

send_formsite_users_to_aweber:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToAweberWorker"
  queue: default

send_api_users_to_adopia:
  cron: "0 * * * *"
  class: "ApiUsers::SendToAdopiaWorker"
  queue: default

send_formsite_users_to_adopia:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToAdopiaWorker"
  queue: default

send_api_users_to_elite:
  cron: "0 * * * *"
  class: "ApiUsers::SendToEliteWorker"
  queue: default

send_formsite_users_to_elite:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEliteWorker"
  queue: default

send_api_users_to_ongage:
  cron: "0 * * * *"
  class: "ApiUsers::SendToOngageWorker"
  queue: default

send_formsite_users_to_ongage:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToOngageWorker"
  queue: default

aweber_migrate_subscribers:
  cron: "0 0 * * *"
  class: "Aweber::MigrateSubscribersWorker"
  queue: default

aweber_collect_statistics:
  cron: "0 0 * * 1,4"
  class: "Aweber::CollectStatisticsWorker"
  queue: statistics

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

