send_api_users_to_esp:
  cron: "0 * * * *"
  class: "ApiUsers::SendToEspWorker"
  queue: default

send_formsite_users_to_esp:
  cron: "0 * * * *"
  class: "FormsiteUsers::SendToEspWorker"
  queue: default

send_leadgen_rev_site_users_to_esp:
  cron: "0 * * * *"
  class: "LeadgenRevSiteUsers::SendToEspWorker"
  queue: default

aweber_migrate_subscribers:
  cron: "0 0 * * *"
  class: "Aweber::MigrateSubscribersWorker"
  queue: default

aweber_collect_statistics:
  cron: "0 0 * * 1,4"
  class: "Aweber::CollectStatisticsWorker"
  queue: statistics

suppression_lists_autoremove_from_esp:
  cron: "0 0  * * *"
  class: "SuppressionLists::AutoremoveFromEspWorker"
  queue: default

batch_send_leads_to_adopia_0:
  cron: "0 1 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: resource

batch_send_leads_to_adopia_1:
  cron: "0 3 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: applyforjobsdirect

batch_send_leads_to_adopia_2:
  cron: "0 5 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: findlocaljobsdirect

batch_send_leads_to_adopia_3:
  cron: "0 7 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: localjobsearchdirect

batch_send_leads_to_adopia_4:
  cron: "0 9 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: resourceassistancenews

batch_send_leads_to_adopia_5:
  cron: "0 11 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: resourcedepotupdates

batch_send_leads_to_adopia_6:
  cron: "0 13 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: findthelocaljobs

batch_send_leads_to_adopia_7:
  cron: "0 15 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: jobsinmyareadirect

batch_send_leads_to_adopia_8:
  cron: "0 17 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: findhousingbenefits

batch_send_leads_to_adopia_9:
  cron: "0 19 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Adopia
    account: findfamilysupport

batch_send_leads_to_aweber_0:
  cron: "0 1 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1058151

batch_send_leads_to_aweber_1:
  cron: "0 3 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1076451

batch_send_leads_to_aweber_2:
  cron: "0 5 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1096361

batch_send_leads_to_aweber_3:
  cron: "0 7 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1110034

batch_send_leads_to_aweber_4:
  cron: "0 9 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1110136

batch_send_leads_to_aweber_5:
  cron: "0 11 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1214105

batch_send_leads_to_aweber_6:
  cron: "0 13 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1142460

batch_send_leads_to_aweber_7:
  cron: "0 15 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1214108

batch_send_leads_to_aweber_8:
  cron: "0 17 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1246184

batch_send_leads_to_aweber_9:
  cron: "0 19 * * *"
  class: "Esp::MassSendLeadsWorker"
  queue: leads
  args:
    provider: Aweber
    account: 1214111
